// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oykmynvwohfillpemflw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95a215bnZ3b2hmaWxscGVtZmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0ODUxNzQsImV4cCI6MjA2MzA2MTE3NH0.AZQFmduv-7jYo6bKRHeyZiFwUuzUrgYWpnDSZYjwiOM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);